### ISSUE TITLE
Changes to Fund 5 Proposal

### ISSUE THREAD

**Issue by stephen-rowan** [Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal#132]
## Changes to Fund 5 Proposal

**Summary** : Change Problem statement to "*A lack of advocacy for open source in a Fund 3 Proposal*", Change Describe your solution to the problem to : "*Community audit of Fund 3 Proposal*", Remove all references to NFT-DAO / Token Rewards, Replace with Community Recognition Token (Ancient Kraken, New Mindflow, Tyler, Dan and Stephen) and new Output to be delivered Departees-Review - Due : 30/06/2021.

### Change Problem statement to :

> A lack of advocacy for open source in a Fund 3 Proposal

### Change Describe your solution to the problem to :

> Community audit of Fund 3 Proposal

### Remove all references to NFT-DAO / Token Rewards

Reason : NFT-DAO is no longer in a position to mint a contribution NFT

### Replace with Community Recognition Token

Budget Requirements : My Budget is broken into $5 for basic costs. 

The minting of an ADA Non-Fungible Token (in an edition of 4) to recognize the community contribution of Ancient Kraken, New Mindflow, Tyler, Dan and Stephen.

### Outputs postponed

The following outputs to be postponed due to work commitments

(3) QA of Ideascale Platform General Issues - Due : 26/05/2021 :
(4) Feedback Challenge : Open-Source Assessment Report - Due : 26/05/2021 :
(5) Project Catalyst Proposal Process Report - Due : 26/05/2021 : 

### Output to be delivered

(7) Departees-Review - Due : 30/06/2021

https://github.com/stephen-rowan/Governance-HOLON/tree/main/Digital-Fortress/NFT-DAO-Departees-Review

**Comment by DanM3rcurius** [comment]
strong stuff, I'll add my review later today!
