### ISSUE TITLE
Comment Raised : Troy (@troy) - "an open-sourced and living project from the outset."

### ISSUE THREAD

**Issue by stephen-rowan** [Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal#20]
###  Troy kudos icon 1 1 day ago (Last edited by Troy 1 day ago)

> Nice! What I love about this proposal is that it is an open-sourced and living project from the outset. It isn't going to sit there static for the next couple of months waiting for the proposer to make updates like all the others: the community can help build the project themselves, immediately. Smart process.

https://cardano.ideascale.com/a/dtd/Quality-Assurance-DAO/351678-48088

### Stephen

Thank-you for your encouraging and insight comment Troy (@troy)

Everything is being tracked in my **F5-Developer-ecosystem-Proposal** (*https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal*) repository including comments from the community (*https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/labels/Community%20Comments*) and **Ideascale process issues** like not being able to bracket text in a URL (*https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/issues/17*) which makes this response look so busy !

This allows for *full transparency* and documents the thought process that goes into a proposal and will help and inform both Community Advisors and Proposers. Anyone who wishes to may download the **Alpha Version 0.0 of my repository in zip format** (*https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/releases/tag/v0.0-alpha*) and I intend to issue new releases at every **proposal milestone** (*https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/milestones*)

All Issues from this Proposal are also **being pushed by a GitHub Bot** to my **#channel on Project Catalyst's Discord** (*https://discordapp.com/channels/756943420660121600/828707796580565003/830931055095316500*) - so GitHub access is not required to follow progress.

**Comment by troy** [comment]
FYI, you're @ mentioning a different Troy than you intend to. I didn't submit this suggestion and have never heard of this project.
