### ISSUE TITLE
FeedbackChallenge : Africa Opensource Pharma & Medicine 

### ISSUE THREAD

**Issue by stephen-rowan** [Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal#63]
## FeedbackChallenge : [Africa Opensource Pharma & Medicine](https://cardano.ideascale.com/a/dtd/Africa-Opensource-Pharma-Medicine/352738-48088)

In the spirit of Project Catalyst's #FeedbackChallenge we are assessing to what extent the Catalyst Funding Process and it's Proposals are **open source** as part of the proposal [Quality-Assurance-DAO](https://cardano.ideascale.com/a/dtd/Quality-Assurance-DAO/351678-48088). Your proposal has been selected because "open source" is mentioned in it's text or comments.

We would appreciate it if you could respond to the following questions (in the reply to my comments below) : 

1.  **Open** - Is your Organisation open-source ?
> Yes.
2.  **Accessible** -  Can community contributors issue pull requests or raise issues on your source code ?
> Yes and we expect and will incentivise for this.
3.  **Transparent** - Can community contributors access and propose changes to the source text of your documentation ?
> Most definitely.

To keep the assessment transparent each comment is recorded as a [GitHub Issue]( https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/issues/63 ) on **Quality-Assurance-DAO's** proposal repository (Apache-2.0 License) where a more detailed explanation can be found. 

Together we can build a community of open source contributors on the Cardano platform.

Thank You 

Stephen Whitenstall, QA-DAO

## Detailed explanation 

Your [Issue reference](https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/issues/63) includes a more detailed explanation of the methodology of this FeedbackChallenge : Open Source. There is also a *Open Source Assessment* [Project Board](https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/projects/3) and a GitHub bot post Issues in my channel #quality-assurance-dao on Project Catalyst's Discord.

We believe this is important because many developers are concerned with the lack of a clear commitment to open source and fear their free contributions will be locked into a proprietary platform.

## Open Source Assessment Method
- [x] Draft a basic Open Source Assessment Method.
https://github.com/Quality-Assurance-DAO/DAO-Open-Source/tree/main/Documents/Assessments

### Basic Open Source Assessment
1.  **Open** - Is your Organisation open-source ?
1.  **Accessible** -  Can your users issue pull requests or raise issues on your organisation's source code ?
1.  **Transparent** -  Can your users access and propose changes to the source of your organisation's documentation ?

### Method
- [x] Do text search of "open source" on Catalyst Projects.
- [x] Post assessment questions in comments of proposal.
- [x] Raise Issue for each proposal's assessment.
- [x] Record response to assessment.
- [ ] Close Issue once proposal submitted and record responses

### Report
- [ ] Collate and publish report of findings with a Creative Commons License

**Comment by drivepilot** [comment]
@stephen-rowan Thank you for your input. We plan on the entire project and all of its inputs and outputs being published in an open source manner. Whilst we love github there is momentum behind another open source biological scientific protocols platform called https://protocols.io that has very specific features for biological protocols that someone would run in a lab. It is essentially attempting to be a github for biology and science. It has an API https://apidoc.protocols.io/ and programmatic access to all of its features so it is likely that we will build a connector to allow bi-directional updates of both platforms. This is likely to be a stretch or medium term goal. Given that there is significant buy in from the scientific community into protocols.io our preference would be to allow either protocols.io or github to be used as a repository for protocols that are used in our project. We need to be cognizant that biologists may not be familiar with the complexities of github and give them platforms they are comfortable with to start.  Open source in biology is complex ( even some reagents or chemicals can have IP associated with them) but we will be working to have everything developed via our platform be published under open source licences. 

So to specifically & succinctly answer your questions.

1. Open - Is your Organisation open-source ?

 **Yes.**

2. Accessible - Can community contributors issue pull requests or raise issues on your source code ?

**Yes and we expect and will incentivise for this.**

3. Transparent - Can community contributors access and propose changes to the source text of your documentation ?
**Most definitely.**

**Comment by drivepilot** [comment]
Protocols.io automatically publish their protocols to github in json & pdf format already, so we can build from that.
https://github.com/protocolsio/protocols/tree/master/protocols

**Comment by stephen-rowan** [comment]
> Hi startupsnyc, (@drivepilot )
> That is great. As you responded directly on GitHub I can close the Issue there. Thanks a lot for your input!
> I think Ideascale is now locked for comments and possibly responses to comments from proposers? 
> I was going to follow up by PM or GitHub. And close the Open-Source Assessment next Wednesday (27th).
> Then I will draft a report and send it to all the commenters for review before publishing. Hopefully it will provide a useful > overview.
> Good Luck with your proposal.

> Stephen

**Comment by stephen-rowan** [comment]
I have captured your response in the body of the original text and moved this issue to "Done".

**Comment by drivepilot** [comment]
Will you also please copy the comment into the comments section on ideascale to demonstrate ongoing activity on our project.

**Comment by stephen-rowan** [comment]
> Andre.Chagwedera (andre.chagwedera) 
> Idea Submitter

> Hi swhitenstall thanks for this and apologies for the delay. My colleague startupsnyc provided a response to the link provided, but thought I would post it here too: swhitenstall Thank you for your input. We plan on the entire project and all of its inputs and outputs being published in an open source manner. Whilst we love github there is momentum behind another open source biological scientific protocols platform called https://protocols.io that has very specific features for biological protocols that someone would run in a lab. It is essentially attempting to be a github for biology and science. It has an API https://apidoc.protocols.io/ and programmatic access to all of its features so it is likely that we will build a connector to allow bi-directional updates of both platforms. This is likely to be a stretch or medium term goal. Given that there is significant buy in from the scientific community into protocols.io our preference would be to allow either protocols.io or github to be used as a repository for protocols that are used in our project. We need to be cognizant that biologists may not be familiar with the complexities of github and give them platforms they are comfortable with to start. Open source in biology is complex ( even some reagents or chemicals can have IP associated with them) but we will be working to have everything developed via our platform be published under open source licences.
So to specifically & succinctly answer your questions.
1) Open - Is your Organisation open-source ?
Yes.
2) Accessible - Can community contributors issue pull requests or raise issues on your source code ?
Yes and we expect and will incentivise for this.
3) Transparent - Can community contributors access and propose changes to the source text of your documentation ?
Most definitely.

**Comment by stephen-rowan** [comment]
Hi Andre.Chagwedera, andre.chagwedera

No need to apologise. Your colleague startupsnyc very helpfully provided a detailed response to my questions (#FeedbackChallenge : Open Source) directly on my proposals repo. Unfortunately, I was unable to post a response here earlier as comments were locked until now.

I can now confirm here that I have captured your comments and friendly responses at https://github.com/Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal/issues/63

I hope to publish an informal report which will provide some overview of Catalyst open source proposals by 26/05/21.

Good Luck with your proposal.

Stephen Whitenstall
